http:
  listener:
    host: "0.0.0.0"
    port: "8085"
  requester:
    fastGo:
      host: "0.0.0.0"
      port: "8084"
      routepath: "/fastGo/routes"
      schedulepath: "/fastGo/schedules"
    travelOnTrip:
      host: "0.0.0.0"
      port: "8083"
      routepath: "/travelOnTrip/routes"
      schedulepath: "/travelOnTrip/schedules"